mozilla-releng/releasewarrior-2.0

releasewarrior/templates/corsica/fennec_beta_progress.template.html
releasewarrior/templates/fennec/beta.json.tmpl

Bug 1417731 added automated emails once the graph has built and moved everything into the candidates directory, so this push 
* removes that task from the template
* updates the corsica template to depend on the next task (pushapk)
I'll need to do the same for Fennec 58 on release, but lets make this is correct first.

Remove 'email candidates' step for Fennec 58 on beta

---

releasewarrior/cli.py
releasewarrior/wiki_data.py

@srfraser @Callek what do you think?
After running:
`release cancel firefox 52.5.1esr`
It committed: https://github.com/mozilla-releng/releasewarrior-data/commit/556acd045d9715ff7eed3778a23933442a16d5d7
and the release was hidden from `release status`.
I then ran:
`release postmortem 2017-12-06`
and it committed: https://github.com/mozilla-releng/releasewarrior-data/commit/52ebbc034bb9ca510813bc464d4f611ab9d024f5

adds command for cancelling a release that have incomplete human tasks

---

releasewarrior/wiki_data.py

This fixes issue #35.
I tested using the STR for both before and after.

'release newbuild' should not mark the new build as aborted, even if previous build is already aborted.

---

.flake8
.taskcluster.yml

Add flake8 support for releasewarrior-2.0; don't actually fix flake8 issues (make the test always pass for now)
We'll need to enable taskcluster integration on mozilla-releng/releasewarrior-2.0 (ala https://tools.taskcluster.net/quickstart/ )

Taskcluster integration

---

releasewarrior/templates/corsica/fennec_release_progress.template.html
releasewarrior/templates/fennec/beta.json.tmpl
releasewarrior/templates/fennec/release.json.tmpl
releasewarrior/templates/firefox/beta.json.tmpl
releasewarrior/templates/firefox/devedition.json.tmpl
releasewarrior/templates/firefox/release-rc.json.tmpl
releasewarrior/templates/firefox/release.json.tmpl
releasewarrior/templates/thunderbird/beta.json.tmpl
releasewarrior/templates/thunderbird/release.json.tmpl

This is built ontop of PR #39 and explicitly doesn't affect fennec release (since its not in-tree relpro) and doesn't affect ESR docs at this time.
(once PR #39 merges, I'll rebase this to `master` to get a clean PR here)

Rw doc linking update

---

releasewarrior/cli.py
releasewarrior/git.py
releasewarrior/helpers.py

Manually updated and newer sha's are fine
This has some guarding around sha format so we don't let ourselves get shell injection due to how `git` proxying may work. And preserves the ability to work off local forks from master of rw2.
The min sha is updated manually in the data repo so humans can determine what is the minimum at any given time (as in, maybe not require a bump for minor bugfixes, terminal output etc, but do require it for any breaking change, etc)

Validate the rw repo version based on a state file in the data repo.

---

extra-requirements-scripts.txt
scripts/get_graphids.py
setup.py

This is first-round at giving a useful gather tasks script. It works by passing in --revision (from any releasy tree) and outputting action tasks in either human form or export form. Future improvements can be to pass in a random taskID from the CI or release graph and find this info without a revision as first input.
I'm particular partial to review of my await/async syntax since this is one of my first uses of that.
Additionally I added `taskcluster` and `aiohttp` to the extras_require section, since its not needed for main releasewarrior2 functionality, but is needed for this script.  `pip install -U -e .['scripts']` works for this locally.

Gather tasks

---

releasewarrior/wiki_data.py

This allows us to display issues that are not marked as resolved in `release status` even when all tasks for the release are complete.
This does not show unresolved issues from build numbers that are not the latest though.
Even without this patch all unresolved issues get displayed as if they are "future threats" in the postmortem though.

Display releases with unresolved issues in status

---

releasewarrior/templates/fennec/release.json.tmpl

@mozbhearsum this is just so we at least still tell the truth for current templates as per: https://github.com/mozilla-releng/releasewarrior-2.0/pull/57#discussion_r165218294

fixes fennec m-r templates to point to temp old docs during 58 cycle

---

docs/CHANGELOG.md
docs/README.md
docs/balrog/Balrog-and-Scheduled-Changes.md
docs/day1/Go-To-Build.md
docs/day1/ReleaseDuty-Day-1-Checklist-and-FAQ.md
docs/development/Maple-(tc-relpro-development---staging).md
docs/mergeduty/howto.md
docs/misc-operations/Purging-the-Partials-Cache.md
docs/release-promotion/desktop/howto.md
docs/release-promotion/desktop/howto_58cycle_and_52esr_only.md
docs/release-promotion/desktop/overview.md
docs/release-promotion/mobile/howto.md
docs/release-promotion/overview.md
docs/signing/Manually-sign-Android-APKs.md

The motivation for this PR lies within [this](https://github.com/mozilla-releng/releasewarrior-2.0/issues/61) issue. More information there, but tl:dr:
- we should have our PR mechanism back
- we can make use of branching and other versioning strategies to separate new docs from old
- centralized place that's structured in an easy-to-grasp-and-search way
This PR does:
* moves all the pages from https://github.com/mozilla-releng/releasewarrior-2.0/wiki into a `docs` subfolder in this repo
* updates CHANGELOG with this change since it's a disruptive major change in the workflow of releaseduty
* corrects several hrefs to cope with the new structure
* reorganizes the docs into a logic subdir structure
If this makes sense, the leftovers & follow items are:
1.announce the CHANGELOG use and …

Bring docs back to warrior

---

docs/development/Maple-(tc-relpro-development---staging).md

Somewhat rambly and not sure if it's 100% coherent, but it's documented now.

add info on how to trigger actions on a newer revision than the builds

---

releasewarrior/templates/fennec/beta.json.tmpl
releasewarrior/templates/fennec/release.json.tmpl
releasewarrior/templates/firefox/beta.json.tmpl
releasewarrior/templates/firefox/devedition.json.tmpl
releasewarrior/templates/firefox/release.json.tmpl
releasewarrior/templates/thunderbird/beta.json.tmpl
releasewarrior/templates/thunderbird/release.json.tmpl

This should reflect the truth of today, even if we were to do a dot release before migration, and covers all situations outside of the rc changes in https://github.com/mozilla-releng/releasewarrior-2.0/pull/68

fixes non rc templates to point to new docs in-repo location

---

releasewarrior/templates/fennec/beta.json.tmpl
releasewarrior/templates/fennec/release.json.tmpl
releasewarrior/templates/firefox/beta.json.tmpl
releasewarrior/templates/firefox/devedition.json.tmpl
releasewarrior/templates/firefox/release.json.tmpl
releasewarrior/templates/thunderbird/beta.json.tmpl
releasewarrior/templates/thunderbird/release.json.tmpl

This builds on https://github.com/mozilla-releng/releasewarrior-2.0/pull/69
https://github.com/mozilla-releng/releasewarrior-2.0/pull/69 can land today but this shouldn't land until we migrate m-r to 59, just like https://github.com/mozilla-releng/releasewarrior-2.0/pull/68

 adds non rc release template updates for 59 

---

releasewarrior/configs/default_config.yaml

Even though the template exists, the command `release track fennec 59.0rc` returns:
``` py
WARNING: no release data state file
INFO: ensuring releasewarrior repo is up to date and in sync with upstream
INFO: generating data from template and config
Traceback (most recent call last):
File "/home/jlorenzo/.virtualenvs/releasewarrior-2.0/bin/release", line 11, in <module>
load_entry_point('releasewarrior', 'console_scripts', 'release')()
File "/home/jlorenzo/.virtualenvs/releasewarrior-2.0/lib/python3.6/site-packages/click-6.7-py3.6.egg/click/core.py", line 722, in __call__
return self.main(*args, **kwargs)
File "/home/jlorenzo/.virtualenvs/releasewarrior-2.0/lib/python3.6/site-packages/click-6.7-py3.6.egg/click/core.py", line 697, in main
rv = self.invoke(ctx)
File …
```

Add Fennec release-rc template in config

---

docs/release-promotion/desktop/howto-rc.md
releasewarrior/templates/firefox/release-rc.json.tmpl
releasewarrior/templates/firefox/release.json.tmpl

I was originally going to write these when we did it for 59.0, but I found some free time to do it today. We can use 59.0 to validate this instead.

Add What's New Page docs

---

docs/release-promotion/desktop/howto-rc.md
releasewarrior/templates/firefox/release-rc.json.tmpl

@jcristau pointed out that we'll need to take extra steps to do this now that we're integrating the WNP into the current Release blob. I think pre-creating a no-WNP blob is simplest way to do this - that way we don't need to teach the automation to publish a different blob as the Fallback Mapping.
I also fixed some links, and moved the WNP set-up earlier in the RC process, since QE has been testing it on release-localtest these days.
@jcristau - I can't flag you for formal review, but feel free to leave feedback.

Add instructions about removing WNP shortly before a new release ships.

---

docs/release-promotion/desktop/historic_relpro.md
releasewarrior/templates/firefox/esr.json.tmpl

The aim is to avoid creating a second graph to push ESR point releases, when we still have that in the original graph and need only resolve the human decision task. Also culls a whole lot of visual noise from the doc to improve readability.

Improve ESR52 push docs

---

docs/CHANGELOG.md
docs/misc-operations/analyze-update-verify-logs.md

This is related to https://bugzilla.mozilla.org/show_bug.cgi?id=1446160, where I've made update verify fail more aggressively, and generate a summary log.
@escapewindow - it's probably good for you to have a look at this too, since you're on releaseduty.

Add documentation for how to interpret update verify results

---

releasewarrior/click_input.py
releasewarrior/wiki_data.py

Do the right thing if you 'copy link' from the new build email, or copy/paste a bugzilla link.

Allow pasting of urls for task groups and bugs

---

releasewarrior/cli.py

Currently, if you type `release` then click truncates most of the help text as part of its `short_help` generation. This PR changes:
```Commands:
cancel      Similar to newbuild where it aborts current...
data
graphid     Add a graphid to a release.
issue       Add or resolve an issue against current...
newbuild    Mark a release as submitted to shipit product...
postmortem  creates a postmortem file based on completed...
prereq      Add or resolve a prerequisite (pre gtb)...
status      shows upcoming prerequisites and inflight...
sync        takes currently saved json data of given...
task        Add or resolve a human task within current...
track       Start tracking an upcoming release.
```
To:
```
Commands:
cancel      Abort the current buildnum.
data        Pushes teh data repo to …
```

Update help text to all fit on one line.

---

docs/release-promotion/mobile/howto-rc.md
docs/release-promotion/mobile/howto.md
releasewarrior/templates/corsica/fennec_beta_progress.template.html
releasewarrior/templates/fennec/beta.json.tmpl

Reverts mozilla-releng/releasewarrior-2.0#137
As it failed in warrior with the following error:
```
(releasewarrior) mtabara@mozspace:[master]~/work/mozilla/clones/git/releasewarrior-2.0$ release track firefox 60.0.2esr
WARNING: no release data state file
INFO: ensuring releasewarrior repo is up to date and in sync with mozilla
INFO: generating data from template and config
INFO: generating wiki from template and config
INFO: writing to data file: /Users/mtabara/work/mozilla/clones/git/releasewarrior-data/upcoming/firefox/firefox-esr60-60.0.2esr.json
INFO: writing to wiki file: /Users/mtabara/work/mozilla/clones/git/releasewarrior-data/upcoming/firefox/firefox-esr60-60.0.2esr.md
INFO: writing to wiki file: /Users/mtabara/work/mozilla/clones/git/releasewarrior-data/README.md
Traceback …
```

Revert "Rename 'pushapk' to 'ship' for Fennec, for consistent naming"

---

releasewarrior/helpers.py

Fixes #17 
Today, I came across several commands that didn't pass because the repo wasn't updated. I hadn't realized it went wrong until I `release status`d. @lundjordan do you think we're comfortable enough to make `pull` the default behavior?

Pull commits from upsteam instead of fetch

---

docs/mergeduty/howto.md

This is not to be merged until after we shipped 62.0 and we're confirmed everything is fine with updating these bouncer entries.
CC'ing @lundjordan.

Bug 1432656 - remove nightly bouncer updates as it is now automated.

---

docs/mergeduty/howto.md

This fixes the central auth issues we've been facing in the last couple of mergeduty cycles. 
Reasoning for this can be found [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1526586#c2).

Bug 1526586 - fix auth issues on bumping central.

---

docs/mergeduty/howto.md

This is a workaround. The longer term is probably to clone enough
that we can run `./mach python` as that's what the other groups
ensure will always work with module moves.

Fix missing/moved modules needed for migration.

---

docs/mergeduty/howto.md

Ideally we no longer need this because we're switching off to automation next cycle, but just in case, for potential fallbacks, let's have this ready.

Bump esr to 68.5.0
