mozilla-releng/releasewarrior-2.0

releasewarrior/helpers.py, releasewarrior/templates/thunderbird/beta.json.tmpl, releasewarrior/templates/thunderbird/release.json.tmpl
I think this is all thats needed @lundjordan .
This should fix issue #3
=> Add thunderbird support

releasewarrior/templates/corsica/fennec_beta_progress.template.html, releasewarrior/templates/corsica/fennec_release_progress.template.html, releasewarrior/templates/corsica/firefox_beta_progress.template.html, releasewarrior/templates/corsica/firefox_devedition_progress.template.html, releasewarrior/templates/corsica/firefox_release_progress.template.html
@rail what do you think?
I know you were looking into a more sophisticated solution including reading json dynamically. However, this should help the confusion about colours.
=> makes all completed steps blue and incomplete muted and white.

releasewarrior/cli.py, releasewarrior/configs/config_example.yaml, releasewarrior/git.py, releasewarrior/templates/markdown/postmortem.md.tmpl, releasewarrior/wiki_data.py
@Callek what do you think?
`release postmortem 2017-11-22` created the following:
https://github.com/mozilla-releng/releasewarrior-data/blob/master/postmortems/2017-11-22.md
I think tomorrow I will edit this so that if there are no future threats (action items), I will remove the table altogether to make the page smaller. Worth noting that this postmortem is awkward because we have supported both warrior tools.
=> Postmortem command and verbose status

releasewarrior/templates/markdown/generic.md.tmpl, releasewarrior/templates/markdown/postmortem.md.tmpl
I haven't modified 'Unblocked' -> 'Blocked' I'm unsure of a nice antonym,
or whether we should invert the bool passed to the template.
=> Update templates, based on feedback in #20

releasewarrior/cli.py, releasewarrior/click_input.py, releasewarrior/helpers.py, releasewarrior/wiki_data.py
=> Update default due date for prereq tasks

releasewarrior/cli.py, releasewarrior/templates/markdown/postmortem.md.tmpl
The postmortem command was broken when I tried it today, so fix that.
Also fix the postmortem doc to group issues together.
=> Improve postmortem doc... fix cli bustage for postmortem command

releasewarrior/cli.py, releasewarrior/helpers.py
=> Validate data repo during status command

old-how-tos/relpro.md, releasewarrior/templates/fennec/beta.json.tmpl, releasewarrior/templates/fennec/release.json.tmpl, releasewarrior/templates/firefox/beta.json.tmpl, releasewarrior/templates/firefox/devedition.json.tmpl, releasewarrior/templates/firefox/esr.json.tmpl, releasewarrior/templates/firefox/release-rc.json.tmpl, releasewarrior/templates/firefox/release.json.tmpl, releasewarrior/templates/thunderbird/beta.json.tmpl, releasewarrior/templates/thunderbird/release.json.tmpl
This updates to use stuff from PR #33 ...  I'm not quite done with this PR and will request a reviewer when done.
=> Update docs for migration to rw2

releasewarrior/configs/config_example.yaml, releasewarrior/wiki_data.py
this was useful for the last two chemspills
=> adds ability to disable corsica

releasewarrior/wiki_data.py
=> if a phase already exists in graphids, let's replace it rather than append

docs/CHANGELOG.md
Wondering if we need an Fx60 section.
=> add balrog scriptworker notes.

releasewarrior/templates/corsica/firefox_release_progress.template.html
I think this might be fallout from one of your recent changes, @MihaiTabara ?
=> Fix template.

releasewarrior/templates/corsica/fennec_release_progress.template.html
Found another one when adding a fennec build
=> fix fennec template

releasewarrior/wiki_data.py
Looks like this fixes the problem, at least in the one test I did locally.
=> Fix graphids being carried forward (fixes #89)

docs/release-promotion/desktop/howto-rc.md
=> Add note about removing platformVersion.

docs/release-promotion/desktop/howto-rc.md
* add more context on the `locales`
* syntax/formatting fixes
* add more information on how to format the blob once it becomes invalid JSON after trimming some of the fields
=> Slightly improve the WNP part 

docs/release-promotion/mobile/howto-rc.md
Aki - sending this review to you just to double check that this was a typo and not intended. Running ship_fennec was what we had to do this morning to ship Fennec.
=> Run the correct phase for fennec ship

docs/release-promotion/desktop/howto-rc.md
I'll be landing that fix next week - we should merge this update at the same time.
=> Update WNP docs now that a fix for https://bugzilla.mozilla.org/show_bug.cgi?id=1431789 is ready

docs/release-promotion/desktop/howto.md, releasewarrior/wiki_data.py
Clearer error messags for invalid task ids, both numeric and string.
=> Issue #111 human task id arguments

docs/release-promotion/mobile/howto.md
A bit unnecessary for fennec, but if we can make the docs all look the same,
we can tell if they can be merged.
=> Change this doc to be more like the others.

releasewarrior/wiki_data.py
Kludgey so far, but it generates a README automatically for the releasewarrior-data repository.  My fork has https://github.com/srfraser/releasewarrior-data/blob/master/README.md now, for example. Hopefully the links to existing releases are useful
=> Create a README automatically in data repo

releasewarrior/templates/markdown/readme.md.tmpl
I'd neglected to add this to  https://github.com/mozilla-releng/releasewarrior-2.0/pull/130
=> Add readme template

releasewarrior/templates/markdown/readme.md.tmpl
=> Fix dictionary sorting in README

scripts/get_graphids.py
https://docs.taskcluster.net/reference/libraries/taskcluster-client.py#list-tasks
=> support latest taskcluster-client index.listtasks method args

docs/release-promotion/mobile/howto-rc.md, docs/release-promotion/mobile/howto.md, releasewarrior/templates/corsica/fennec_beta_progress.template.html, releasewarrior/templates/fennec/beta.json.tmpl
We'll need to update any inflight releases in the data repo when this lands.
=> Rename 'pushapk' to 'ship' for Fennec, for consistent naming

docs/release-promotion/desktop/ubuntu-snap.md
=> Bug 1467261 - Snap: add instructions about who ships and when

releasewarrior/helpers.py
=> Fix lint issue

releasewarrior/templates/corsica/fennec_beta_progress.template.html, releasewarrior/templates/corsica/fennec_release_progress.template.html, releasewarrior/templates/corsica/firefox_beta_progress.template.html, releasewarrior/templates/corsica/firefox_devedition_progress.template.html, releasewarrior/templates/corsica/firefox_release_progress.template.html, releasewarrior/wiki_data.py
Fixes #179 
This displays all release under the folder "inflight" even the completed ones.
=> Fix previous release from taking over existing one in index.html

releasewarrior/cli.py, releasewarrior/wiki_data.py
=> Display preflight tasks even when release started

docs/CHANGELOG.md
@tomprince @JohanLorenzo Do you remember any other important changes worth mentioning in the `CHANGELOG` that happened during 62.0? Feel free to amend this PR as well, am not sure if I framed things right.
=> Bring Changelog up-to-date for 62.0 release cycle

docs/mergeduty/howto.md
Doc fixes for https://github.com/mozilla-releng/releasewarrior-2.0/pull/211
=> Wnp fixes; depends on #211

docs/CHANGELOG.md, docs/mergeduty/howto.md
I'll follow-up next week after we have some more answers to some of the TODs to streamline the process.
=> First part of fixing the docs. 

docs/mergeduty/howto.md
=> Remove mention of merge day instance
